# Project configuration
spring:
  application:
    name: j_booking

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  # DB configuration
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5435/${POSTGRES_DB:j_booking}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:validate}
    show-sql: ${SPRING_JPA_SHOW_SQL:true}
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
        default_schema: public

  flyway:
    enabled: true
    baseline-on-migrate: true

  # Redis configuration
  cache:
    type: redis
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      lettuce:
        pool:
          max-active: ${REDIS_POOL_LETTUCE_MAX_ACTIVE:32}
          max-idle: ${REDIS_POOL_LETTUCE_MAX_IDLE:16}
          min-idle: ${REDIS_POOL_LETTUCE_MIN_IDLE:8}
          max-wait: ${REDIS_POOL_LETTUCE_MAX_WAIT:2000}
      database: 0
      timeout: ${REDIS_CONNECT_TIMEOUT:2000}

      default-ttl: ${REDIS_DEFAULT_TTL:30000}
      order-ttl: ${REDIS_ORDER_TTL:5000}
      merchant-ttl: ${REDIS_MERCHANT_TTL:5000}

# Tomcat configuration
server:
  port: ${SERVER_PORT:8080} # В .env у тебя 8080
  tomcat:
    accept-count: ${TOMCAT_ACCEPT_COUNT:100}
    max-connections: ${TOMCAT_MAX_CONNECTIONS:1000}
    threads:
      max: ${TOMCAT_MAX_THREADS:200}
      min-spare: ${TOMCAT_MIN_SPARE_THREADS:20}

# Kafka
kafka:
  bootstrapServers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
  groupId: ${KAFKA_CARD_GROUP_ID:j-booking-group}
  clientId: ${KAFKA_CARD_CLIENT_ID:j-booking-client}
  acksConfig: ${KAFKA_ACKS_CONFIG:all}
  retriesConfig: ${KAFKA_RETRIES_CONFIG:3}
  lingerMsConfig: ${KAFKA_LINGER_MS_CONFIG:100}
  clientDnsLookup: ${KAFKA_CLIENT_DNS_LOOKUP:use_all_dns_ips}
  batchSizeConfig: ${KAFKA_BATCH_SIZE_CONFIG:16384}
  bufferMemoryConfig: ${KAFKA_BUFFER_MEMORY_CONFIG:32768}
  autoOffsetResetConfig: ${KAFKA_AUTO_OFFSET_RESET_CONFIG:earliest}